// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_service.proto

package users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeRequest) Reset()         { *m = GetMeRequest{} }
func (m *GetMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMeRequest) ProtoMessage()    {}
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{0}
}

func (m *GetMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeRequest.Unmarshal(m, b)
}
func (m *GetMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeRequest.Marshal(b, m, deterministic)
}
func (m *GetMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeRequest.Merge(m, src)
}
func (m *GetMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMeRequest.Size(m)
}
func (m *GetMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeRequest proto.InternalMessageInfo

type User struct {
	// Name of the resource, for example "users/user1".
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2683e726c16c873, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMeRequest)(nil), "app.miniboard.users.v1.GetMeRequest")
	proto.RegisterType((*User)(nil), "app.miniboard.users.v1.User")
}

func init() { proto.RegisterFile("users_service.proto", fileDescriptor_e2683e726c16c873) }

var fileDescriptor_e2683e726c16c873 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0x2a, 0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x4b, 0x2c, 0x28, 0xd0, 0xcb, 0xcd, 0xcc, 0xcb, 0x4c, 0xca, 0x4f, 0x2c, 0x4a, 0xd1, 0x03,
	0x2b, 0xd1, 0x2b, 0x33, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8,
	0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xe8, 0x52, 0xe2,
	0xe3, 0xe2, 0x71, 0x4f, 0x2d, 0xf1, 0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x92,
	0xe2, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x8d, 0x4a, 0xb9, 0x78, 0x40, 0x72, 0xc5, 0xc1, 0x10,
	0x7b, 0x85, 0x52, 0xb9, 0x58, 0xc1, 0x7a, 0x85, 0x54, 0xf4, 0xb0, 0xdb, 0xad, 0x87, 0x6c, 0xb4,
	0x94, 0x0c, 0x2e, 0x55, 0x20, 0x43, 0x95, 0x24, 0x9a, 0x2e, 0x3f, 0x99, 0xcc, 0x24, 0x24, 0x24,
	0x00, 0x76, 0x68, 0x99, 0xa1, 0x3e, 0x58, 0x5a, 0x3f, 0x37, 0xd5, 0x89, 0x3d, 0x8a, 0x15, 0xcc,
	0x4e, 0x62, 0x03, 0x3b, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x72, 0x19, 0xd0, 0xff,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	// Get me
	//
	// Returns logged in user.
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*User, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.v1.UsersService/GetMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	// Get me
	//
	// Returns logged in user.
	GetMe(context.Context, *GetMeRequest) (*User, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) GetMe(ctx context.Context, req *GetMeRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.v1.UsersService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.users.v1.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _UsersService_GetMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_service.proto",
}
