run:
  timeout: 5m
  skip-dirs-use-default: true
  skip-files:
    - "genproto/.*$"

linters:
  disable:
    - staticcheck
    - goprintffuncname
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - gocognit
    - maligned
    - prealloc
    - gosec
  # - wsl
    - funlen
  # - gomnd
  # - godox
  # - lll
  # - interfacer
    - scopelint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - gocognit
        - unparam
        - gochecknoglobals
        - goconst
    - path: db/migrations.go
      linters:
        - funlen
    - path: subscriptions/db.go
      linters:
        - funlen
    - path: items/db.go
      linters:
        - funlen
    - path: backend.go
      linters:
        - funlen
