run:
  timeout: 1m

linters:
  enable-all: true
  disable:
    - gci
    - godot
    - gofumpt
    - lll
    - wsl
    - exhaustivestruct
    - goerr113
    - gomnd
    - goprintffuncname
    - nlreturn
    - sqlclosecheck
    - testpackage
    - thelper
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - gocognit
        - unparam
        - gochecknoglobals
        - goconst
        - funlen
    - path: db/migrations.go
      linters:
        - funlen
    - path: subscriptions/db.go
      linters:
        - funlen
    - path: items/db.go
      linters:
        - funlen
    - path: backend.go
      linters:
        - funlen
