authorizations:
  domain: "localhost"
  cookie_lifetime: 24h
http:
  addr: ":80"
cors:
  domains: ["http://localhost:8080"]
db:
  driver: sqlite3
  addr: "./db.dev.sqlite3?_journal_mode=WAL"
  max_open_connections: 1
