kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: redis
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
