apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-do-prod
 namespace: cert-manager
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: nikita+letsencrypt@galaiko.rocks
   privateKeySecretRef:
     name: letsencrypt
   solvers:
   - dns01:
       digitalocean:
         tokenSecretRef:
           name: digitalocean-dns
           key: access-token
