// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feeds_service.proto

package feeds

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFeedRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedRequest) Reset()         { *m = GetFeedRequest{} }
func (m *GetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRequest) ProtoMessage()    {}
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{0}
}

func (m *GetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedRequest.Unmarshal(m, b)
}
func (m *GetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRequest.Merge(m, src)
}
func (m *GetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedRequest.Size(m)
}
func (m *GetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRequest proto.InternalMessageInfo

func (m *GetFeedRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListFeedsRequest struct {
	// The maximum number of feeds to return.
	PageSize int64 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFeedsRequest) Reset()         { *m = ListFeedsRequest{} }
func (m *ListFeedsRequest) String() string { return proto.CompactTextString(m) }
func (*ListFeedsRequest) ProtoMessage()    {}
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{1}
}

func (m *ListFeedsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeedsRequest.Unmarshal(m, b)
}
func (m *ListFeedsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeedsRequest.Marshal(b, m, deterministic)
}
func (m *ListFeedsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeedsRequest.Merge(m, src)
}
func (m *ListFeedsRequest) XXX_Size() int {
	return xxx_messageInfo_ListFeedsRequest.Size(m)
}
func (m *ListFeedsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeedsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeedsRequest proto.InternalMessageInfo

func (m *ListFeedsRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListFeedsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListFeedsResponse struct {
	// There will be a maximum number of feeds returned based on the page_size field int the request.
	Feeds []*Feed `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFeedsResponse) Reset()         { *m = ListFeedsResponse{} }
func (m *ListFeedsResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeedsResponse) ProtoMessage()    {}
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{2}
}

func (m *ListFeedsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeedsResponse.Unmarshal(m, b)
}
func (m *ListFeedsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeedsResponse.Marshal(b, m, deterministic)
}
func (m *ListFeedsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeedsResponse.Merge(m, src)
}
func (m *ListFeedsResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeedsResponse.Size(m)
}
func (m *ListFeedsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeedsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeedsResponse proto.InternalMessageInfo

func (m *ListFeedsResponse) GetFeeds() []*Feed {
	if m != nil {
		return m.Feeds
	}
	return nil
}

func (m *ListFeedsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Feed struct {
	// Name of the resource, for example "users/user1/feeds/feed1".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Time of the last feed fetch by the reader.
	LastFetched *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_fetched,json=lastFetched,proto3" json:"last_fetched,omitempty"`
	// Url is the feed's url.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Title is the feed's title.
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feed) Reset()         { *m = Feed{} }
func (m *Feed) String() string { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()    {}
func (*Feed) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{3}
}

func (m *Feed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feed.Unmarshal(m, b)
}
func (m *Feed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feed.Marshal(b, m, deterministic)
}
func (m *Feed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feed.Merge(m, src)
}
func (m *Feed) XXX_Size() int {
	return xxx_messageInfo_Feed.Size(m)
}
func (m *Feed) XXX_DiscardUnknown() {
	xxx_messageInfo_Feed.DiscardUnknown(m)
}

var xxx_messageInfo_Feed proto.InternalMessageInfo

func (m *Feed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feed) GetLastFetched() *timestamp.Timestamp {
	if m != nil {
		return m.LastFetched
	}
	return nil
}

func (m *Feed) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Feed) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*GetFeedRequest)(nil), "app.miniboard.users.feeds.v1.GetFeedRequest")
	proto.RegisterType((*ListFeedsRequest)(nil), "app.miniboard.users.feeds.v1.ListFeedsRequest")
	proto.RegisterType((*ListFeedsResponse)(nil), "app.miniboard.users.feeds.v1.ListFeedsResponse")
	proto.RegisterType((*Feed)(nil), "app.miniboard.users.feeds.v1.Feed")
}

func init() { proto.RegisterFile("feeds_service.proto", fileDescriptor_31efcc759eeb2667) }

var fileDescriptor_31efcc759eeb2667 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0xa6, 0x63, 0xf4, 0x75, 0xc0, 0x30, 0x20, 0xa2, 0xb0, 0x41, 0x15, 0xa1, 0x69,
	0x9a, 0x90, 0xad, 0x95, 0x0b, 0x97, 0x5d, 0x38, 0x8c, 0x0b, 0x42, 0x28, 0xdb, 0x89, 0x4b, 0xe4,
	0x2e, 0xaf, 0xc5, 0x22, 0xb1, 0x43, 0xec, 0x54, 0xa8, 0x88, 0x03, 0x70, 0xe4, 0xc8, 0x37, 0xe0,
	0x2b, 0xf1, 0x15, 0xf8, 0x20, 0x28, 0xcf, 0x4d, 0x45, 0x01, 0x55, 0xbd, 0xd9, 0xcf, 0x3f, 0x3f,
	0xbf, 0xff, 0xff, 0x6f, 0xb8, 0x33, 0x45, 0xcc, 0x6d, 0x66, 0xb1, 0x9e, 0xab, 0x2b, 0xe4, 0x55,
	0x6d, 0x9c, 0x61, 0x07, 0xb2, 0xaa, 0x78, 0xa9, 0xb4, 0x9a, 0x18, 0x59, 0xe7, 0xbc, 0xb1, 0x58,
	0x5b, 0x4e, 0x20, 0x9f, 0x9f, 0xc6, 0x07, 0x33, 0x63, 0x66, 0x05, 0x0a, 0x59, 0x29, 0x21, 0xb5,
	0x36, 0x4e, 0x3a, 0x65, 0xb4, 0xf5, 0x77, 0xe3, 0x47, 0xcb, 0x53, 0xda, 0x4d, 0x9a, 0xa9, 0x70,
	0xaa, 0x44, 0xeb, 0x64, 0x59, 0x79, 0x20, 0x79, 0x0c, 0x37, 0x5f, 0xa0, 0x3b, 0x47, 0xcc, 0x53,
	0x7c, 0xdf, 0xa0, 0x75, 0x8c, 0x41, 0x5f, 0xcb, 0x12, 0xa3, 0x60, 0x14, 0x1c, 0x0f, 0x52, 0x5a,
	0x27, 0xaf, 0x60, 0xff, 0xa5, 0xb2, 0x84, 0xd9, 0x8e, 0x7b, 0x00, 0x83, 0x4a, 0xce, 0x30, 0xb3,
	0x6a, 0xe1, 0xe1, 0x30, 0xbd, 0xde, 0x16, 0x2e, 0xd4, 0x02, 0xd9, 0x21, 0x00, 0x1d, 0x3a, 0xf3,
	0x0e, 0x75, 0xd4, 0xa3, 0x56, 0x84, 0x5f, 0xb6, 0x85, 0xa4, 0x81, 0xdb, 0x7f, 0xf4, 0xb3, 0x95,
	0xd1, 0x16, 0xd9, 0x33, 0xd8, 0x21, 0x55, 0x51, 0x30, 0x0a, 0x8f, 0x87, 0xe3, 0x84, 0x6f, 0xd2,
	0xcd, 0x69, 0x64, 0x7f, 0x81, 0x1d, 0xc1, 0x2d, 0x8d, 0x1f, 0x5c, 0xf6, 0xcf, 0x93, 0x37, 0xda,
	0xf2, 0xeb, 0xd5, 0xb3, 0x9f, 0x03, 0xe8, 0xb7, 0xf7, 0xfe, 0xa7, 0x91, 0x9d, 0xc1, 0x5e, 0x21,
	0xad, 0xcb, 0xa6, 0xe8, 0xae, 0xde, 0x62, 0x4e, 0x1d, 0x86, 0xe3, 0x98, 0x7b, 0x07, 0x79, 0xe7,
	0x20, 0xbf, 0xec, 0x1c, 0x4c, 0x87, 0x2d, 0x7f, 0xee, 0x71, 0xb6, 0x0f, 0x61, 0x53, 0x17, 0x51,
	0x48, 0x1d, 0xdb, 0x25, 0xbb, 0x0b, 0x3b, 0x4e, 0xb9, 0x02, 0xa3, 0x3e, 0xd5, 0xfc, 0x66, 0xfc,
	0xa3, 0x07, 0x7b, 0xa4, 0xfb, 0xc2, 0x87, 0xcc, 0xbe, 0x06, 0xb0, 0xbb, 0x8c, 0x80, 0x3d, 0xd9,
	0xac, 0x79, 0x3d, 0xa9, 0x78, 0x0b, 0x87, 0x92, 0xa3, 0x2f, 0x3f, 0x7f, 0x7d, 0xef, 0x8d, 0xd8,
	0x43, 0xfa, 0x20, 0xf3, 0x53, 0xf1, 0xb1, 0x15, 0x7b, 0x46, 0xa8, 0x38, 0x11, 0x04, 0x8b, 0x93,
	0x4f, 0xec, 0x5b, 0x00, 0x83, 0x55, 0x24, 0x8c, 0x6f, 0xee, 0xfc, 0xf7, 0x5f, 0x88, 0xc5, 0xd6,
	0xbc, 0xcf, 0x3a, 0x39, 0xa4, 0xb1, 0xee, 0xb3, 0x7b, 0xdd, 0x58, 0x6b, 0x03, 0x3d, 0xdf, 0x7d,
	0xe3, 0x93, 0x9d, 0x5c, 0x23, 0xdb, 0x9f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x41, 0x3e,
	0xb9, 0x19, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedsServiceClient is the client API for FeedsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedsServiceClient interface {
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*Feed, error)
	ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error)
}

type feedsServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedsServiceClient(cc *grpc.ClientConn) FeedsServiceClient {
	return &feedsServiceClient{cc}
}

func (c *feedsServiceClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*Feed, error) {
	out := new(Feed)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.feeds.v1.FeedsService/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error) {
	out := new(ListFeedsResponse)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.feeds.v1.FeedsService/ListFeeds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedsServiceServer is the server API for FeedsService service.
type FeedsServiceServer interface {
	GetFeed(context.Context, *GetFeedRequest) (*Feed, error)
	ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error)
}

// UnimplementedFeedsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFeedsServiceServer struct {
}

func (*UnimplementedFeedsServiceServer) GetFeed(ctx context.Context, req *GetFeedRequest) (*Feed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (*UnimplementedFeedsServiceServer) ListFeeds(ctx context.Context, req *ListFeedsRequest) (*ListFeedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeeds not implemented")
}

func RegisterFeedsServiceServer(s *grpc.Server, srv FeedsServiceServer) {
	s.RegisterService(&_FeedsService_serviceDesc, srv)
}

func _FeedsService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.feeds.v1.FeedsService/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.feeds.v1.FeedsService/ListFeeds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).ListFeeds(ctx, req.(*ListFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.users.feeds.v1.FeedsService",
	HandlerType: (*FeedsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeed",
			Handler:    _FeedsService_GetFeed_Handler,
		},
		{
			MethodName: "ListFeeds",
			Handler:    _FeedsService_ListFeeds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeds_service.proto",
}
