kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
data:
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-early-data: "true"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress
  labels:
    app: nginx-ingress

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
