// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rss_service.proto

package rss

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feed struct {
	// Name of the resource, for example "users/user1/feeds/feed1".
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feed) Reset()         { *m = Feed{} }
func (m *Feed) String() string { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()    {}
func (*Feed) Descriptor() ([]byte, []int) {
	return fileDescriptor_2940ccdfc1dcaa8e, []int{0}
}

func (m *Feed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feed.Unmarshal(m, b)
}
func (m *Feed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feed.Marshal(b, m, deterministic)
}
func (m *Feed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feed.Merge(m, src)
}
func (m *Feed) XXX_Size() int {
	return xxx_messageInfo_Feed.Size(m)
}
func (m *Feed) XXX_DiscardUnknown() {
	xxx_messageInfo_Feed.DiscardUnknown(m)
}

var xxx_messageInfo_Feed proto.InternalMessageInfo

func (m *Feed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Feed)(nil), "app.miniboard.users.rss.v1.Feed")
}

func init() { proto.RegisterFile("rss_service.proto", fileDescriptor_2940ccdfc1dcaa8e) }

var fileDescriptor_2940ccdfc1dcaa8e = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2a, 0x2e, 0x8e,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4a,
	0x2c, 0x28, 0xd0, 0xcb, 0xcd, 0xcc, 0xcb, 0x4c, 0xca, 0x4f, 0x2c, 0x4a, 0xd1, 0x2b, 0x2d, 0x4e,
	0x2d, 0x2a, 0xd6, 0x2b, 0x2a, 0x2e, 0xd6, 0x2b, 0x33, 0x54, 0x92, 0xe2, 0x62, 0x71, 0x4b, 0x4d,
	0x4d, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x8d, 0x78, 0xb8, 0xb8, 0x82, 0x82, 0x83, 0x83, 0x21, 0x66, 0x39, 0xb1, 0x46, 0x31,
	0x17, 0x15, 0x17, 0x27, 0xb1, 0x81, 0xcd, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x2c,
	0xb2, 0xb0, 0x68, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RSSServiceClient is the client API for RSSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RSSServiceClient interface {
}

type rSSServiceClient struct {
	cc *grpc.ClientConn
}

func NewRSSServiceClient(cc *grpc.ClientConn) RSSServiceClient {
	return &rSSServiceClient{cc}
}

// RSSServiceServer is the server API for RSSService service.
type RSSServiceServer interface {
}

// UnimplementedRSSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRSSServiceServer struct {
}

func RegisterRSSServiceServer(s *grpc.Server, srv RSSServiceServer) {
	s.RegisterService(&_RSSService_serviceDesc, srv)
}

var _RSSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.users.rss.v1.RSSService",
	HandlerType: (*RSSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "rss_service.proto",
}
