// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/auth/v1/auth_service.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Authentication_Type int32

const (
	// Invalid authentication.
	Authentication_TYPE_UNKNOWN Authentication_Type = 0
	// Bearer authentication.
	Authentication_TYPE_BEARER Authentication_Type = 1
)

var Authentication_Type_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_BEARER",
}

var Authentication_Type_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"TYPE_BEARER":  1,
}

func (x Authentication_Type) String() string {
	return proto.EnumName(Authentication_Type_name, int32(x))
}

func (Authentication_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bf731f9140610c7, []int{1, 0}
}

type CreateAuthenticationRequest struct {
	// User resource name.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Password.
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthenticationRequest) Reset()         { *m = CreateAuthenticationRequest{} }
func (m *CreateAuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuthenticationRequest) ProtoMessage()    {}
func (*CreateAuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf731f9140610c7, []int{0}
}

func (m *CreateAuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthenticationRequest.Unmarshal(m, b)
}
func (m *CreateAuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthenticationRequest.Merge(m, src)
}
func (m *CreateAuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuthenticationRequest.Size(m)
}
func (m *CreateAuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthenticationRequest proto.InternalMessageInfo

func (m *CreateAuthenticationRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateAuthenticationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Authentication struct {
	// Name of the resource, for example "authentications/authentication1".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the authorization.
	Type Authentication_Type `protobuf:"varint,2,opt,name=type,proto3,enum=app.miniboard.users.auth.v1.Authentication_Type" json:"type,omitempty"`
	// Authorization token.
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}
func (*Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf731f9140610c7, []int{1}
}

func (m *Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authentication.Unmarshal(m, b)
}
func (m *Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authentication.Marshal(b, m, deterministic)
}
func (m *Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authentication.Merge(m, src)
}
func (m *Authentication) XXX_Size() int {
	return xxx_messageInfo_Authentication.Size(m)
}
func (m *Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Authentication proto.InternalMessageInfo

func (m *Authentication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Authentication) GetType() Authentication_Type {
	if m != nil {
		return m.Type
	}
	return Authentication_TYPE_UNKNOWN
}

func (m *Authentication) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("app.miniboard.users.auth.v1.Authentication_Type", Authentication_Type_name, Authentication_Type_value)
	proto.RegisterType((*CreateAuthenticationRequest)(nil), "app.miniboard.users.auth.v1.CreateAuthenticationRequest")
	proto.RegisterType((*Authentication)(nil), "app.miniboard.users.auth.v1.Authentication")
}

func init() { proto.RegisterFile("users/auth/v1/auth_service.proto", fileDescriptor_3bf731f9140610c7) }

var fileDescriptor_3bf731f9140610c7 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x2d, 0x4e, 0x2d,
	0x2a, 0xd6, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2f, 0x33, 0x04, 0xd3, 0xf1, 0xc5, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xd2, 0x89, 0x05, 0x05, 0x7a, 0xb9,
	0x99, 0x79, 0x99, 0x49, 0xf9, 0x89, 0x45, 0x29, 0x7a, 0x60, 0xf5, 0x7a, 0x20, 0x75, 0x7a, 0x65,
	0x86, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79,
	0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0xad, 0x4a, 0x81, 0x5c, 0xd2, 0xce,
	0x45, 0xa9, 0x89, 0x25, 0xa9, 0x8e, 0xa5, 0x25, 0x19, 0xa9, 0x79, 0x25, 0x99, 0xc9, 0x60, 0xe9,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0x82, 0xc4, 0xa2, 0xd4, 0xbc,
	0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0xa3, 0x20, 0xb1,
	0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x2c, 0x03, 0xe7, 0x2b, 0xad, 0x66, 0xe4, 0xe2,
	0x43, 0x35, 0x4d, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x15, 0x6a, 0x08, 0x98, 0x2d, 0xe4,
	0xc2, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x0a, 0xd6, 0xce, 0x67, 0x64, 0xa0, 0x87, 0xc7, 0x0f, 0x7a,
	0xa8, 0xc6, 0xe9, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x75, 0x0b, 0x89, 0x70, 0xb1, 0x96, 0xe4,
	0x67, 0xa7, 0xe6, 0x49, 0x30, 0x83, 0x8d, 0x86, 0x70, 0x94, 0x34, 0xb9, 0x58, 0x40, 0x6a, 0x84,
	0x04, 0xb8, 0x78, 0x42, 0x22, 0x03, 0x5c, 0xe3, 0x43, 0xfd, 0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0x04,
	0x18, 0x84, 0xf8, 0xb9, 0xb8, 0xc1, 0x22, 0x4e, 0xae, 0x8e, 0x41, 0xae, 0x41, 0x02, 0x8c, 0x46,
	0xfb, 0x19, 0xb9, 0xb8, 0x41, 0xc6, 0x07, 0x43, 0x42, 0x54, 0x68, 0x3d, 0x23, 0x97, 0x08, 0xb6,
	0x10, 0x11, 0xb2, 0xc0, 0xeb, 0x42, 0x3c, 0x81, 0x28, 0xa5, 0x4d, 0x82, 0xdf, 0x94, 0x0c, 0x9a,
	0x2e, 0x3f, 0x99, 0xcc, 0xa4, 0xa5, 0xa4, 0x01, 0x8e, 0xb0, 0x32, 0x43, 0xfd, 0x6a, 0x48, 0x90,
	0xdb, 0x42, 0x52, 0x81, 0x56, 0x2d, 0x38, 0x01, 0x20, 0x34, 0x14, 0x3b, 0xb1, 0x45, 0xb1, 0x80,
	0x84, 0x92, 0xd8, 0xc0, 0x31, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x70, 0x14, 0x03,
	0x30, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Create Authentication
	//
	// Returns a user authentication.
	CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*Authentication, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*Authentication, error) {
	out := new(Authentication)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.auth.v1.AuthService/CreateAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// Create Authentication
	//
	// Returns a user authentication.
	CreateAuthentication(context.Context, *CreateAuthenticationRequest) (*Authentication, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CreateAuthentication(ctx context.Context, req *CreateAuthenticationRequest) (*Authentication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthentication not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CreateAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.auth.v1.AuthService/CreateAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateAuthentication(ctx, req.(*CreateAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.users.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthentication",
			Handler:    _AuthService_CreateAuthentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/auth/v1/auth_service.proto",
}
