apiVersion: v1
kind: Namespace
metadata:
  name: miniboard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniboard
  namespace: miniboard
  labels:
    app: miniboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniboard
  template:
    metadata:
      namespace: miniboard
      labels:
        app: miniboard
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: miniflux
        image: docker.pkg.github.com/ngalaiko/miniboard/app:{{ .Values.Version }}
        ports:
        - containerPort: 8443
          name: https
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: https
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        args:
          - --addr=:8443
          - --redis-uri=redis.redis:6379
          - --smtp-sender=auth@miniboard.app
          - --smtp-port=587
          - --smtp-host=smtp.fastmail.com
          - --domain=https://miniboard.app
          - --ssl-cert=/tls/tls.crt
          - --ssl-key=/tls/tls.key
        env:
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: smtp-username
                key: SMTP_USERNAME
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smtp-password
                key: SMTP_PASSWORD
        volumeMounts:
        - name: tls-certificate
          mountPath: /tls

      volumes:
      - name: tls-certificate
        secret:
          secretName: tls-certificate
