// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentications/v1/authentication_service.proto

package authenticaton

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Authentication_Type int32

const (
	// Invalid authentication.
	Authentication_TYPE_UNKNOWN Authentication_Type = 0
	// Bearer authentication.
	Authentication_TYPE_BEARER Authentication_Type = 1
)

var Authentication_Type_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_BEARER",
}

var Authentication_Type_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"TYPE_BEARER":  1,
}

func (x Authentication_Type) String() string {
	return proto.EnumName(Authentication_Type_name, int32(x))
}

func (Authentication_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc74f6a7c14475f3, []int{1, 0}
}

type CreateAuthenticationRequest struct {
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password.
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthenticationRequest) Reset()         { *m = CreateAuthenticationRequest{} }
func (m *CreateAuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuthenticationRequest) ProtoMessage()    {}
func (*CreateAuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc74f6a7c14475f3, []int{0}
}

func (m *CreateAuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthenticationRequest.Unmarshal(m, b)
}
func (m *CreateAuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthenticationRequest.Merge(m, src)
}
func (m *CreateAuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuthenticationRequest.Size(m)
}
func (m *CreateAuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthenticationRequest proto.InternalMessageInfo

func (m *CreateAuthenticationRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAuthenticationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Authentication struct {
	// Name of the resource, for example "authentications/authentication1".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the authorization.
	Type Authentication_Type `protobuf:"varint,2,opt,name=type,proto3,enum=app.miniboard.authentications.v1.Authentication_Type" json:"type,omitempty"`
	// Authorization token.
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}
func (*Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc74f6a7c14475f3, []int{1}
}

func (m *Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authentication.Unmarshal(m, b)
}
func (m *Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authentication.Marshal(b, m, deterministic)
}
func (m *Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authentication.Merge(m, src)
}
func (m *Authentication) XXX_Size() int {
	return xxx_messageInfo_Authentication.Size(m)
}
func (m *Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Authentication proto.InternalMessageInfo

func (m *Authentication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Authentication) GetType() Authentication_Type {
	if m != nil {
		return m.Type
	}
	return Authentication_TYPE_UNKNOWN
}

func (m *Authentication) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("app.miniboard.authentications.v1.Authentication_Type", Authentication_Type_name, Authentication_Type_value)
	proto.RegisterType((*CreateAuthenticationRequest)(nil), "app.miniboard.authentications.v1.CreateAuthenticationRequest")
	proto.RegisterType((*Authentication)(nil), "app.miniboard.authentications.v1.Authentication")
}

func init() {
	proto.RegisterFile("authentications/v1/authentication_service.proto", fileDescriptor_dc74f6a7c14475f3)
}

var fileDescriptor_dc74f6a7c14475f3 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0x2c, 0x2d, 0xc9,
	0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2f, 0x33, 0x44, 0x13,
	0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52,
	0x48, 0x2c, 0x28, 0xd0, 0xcb, 0xcd, 0xcc, 0xcb, 0x4c, 0xca, 0x4f, 0x2c, 0x4a, 0xd1, 0x43, 0xd3,
	0xae, 0x57, 0x66, 0x28, 0x25, 0x93, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9,
	0x9f, 0x98, 0x97, 0x97, 0x5f, 0x02, 0x95, 0x02, 0xeb, 0x57, 0x0a, 0xe5, 0x92, 0x76, 0x2e, 0x4a,
	0x4d, 0x2c, 0x49, 0x75, 0x44, 0xd1, 0x19, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc5,
	0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0xe7, 0x83, 0xe4, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0x20, 0x72,
	0x30, 0xbe, 0xd2, 0x06, 0x46, 0x2e, 0x3e, 0x54, 0x13, 0x85, 0x84, 0xb8, 0x58, 0x90, 0x8c, 0x01,
	0xb3, 0x85, 0x3c, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0xc1, 0xda, 0xf9, 0x8c, 0x4c, 0xf5, 0x08,
	0x79, 0x46, 0x0f, 0xd5, 0x4c, 0xbd, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0x11, 0x42, 0x22, 0x5c,
	0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0xcc, 0x60, 0xf3, 0x21, 0x1c, 0x25, 0x4d, 0x2e, 0x16,
	0x90, 0x1a, 0x21, 0x01, 0x2e, 0x9e, 0x90, 0xc8, 0x00, 0xd7, 0xf8, 0x50, 0x3f, 0x6f, 0x3f, 0xff,
	0x70, 0x3f, 0x01, 0x06, 0x21, 0x7e, 0x2e, 0x6e, 0xb0, 0x88, 0x93, 0xab, 0x63, 0x90, 0x6b, 0x90,
	0x00, 0xa3, 0xd1, 0x61, 0x46, 0x2e, 0x31, 0x54, 0xe3, 0x8b, 0x83, 0x21, 0x41, 0x2d, 0xb4, 0x82,
	0x91, 0x4b, 0x04, 0x5b, 0x28, 0x09, 0xd9, 0x12, 0x76, 0x31, 0x9e, 0xd0, 0x95, 0x32, 0x20, 0xd5,
	0xc3, 0x4a, 0xf2, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x92, 0x54, 0x12, 0x07, 0x47, 0x27, 0x46, 0xe2,
	0x28, 0x76, 0xe2, 0x8f, 0xe2, 0x45, 0x12, 0xca, 0xcf, 0x4b, 0x62, 0x03, 0xc7, 0xb3, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x17, 0xfb, 0xe2, 0x1d, 0x5a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticationsServiceClient is the client API for AuthenticationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationsServiceClient interface {
	// Authenticate
	//
	// Returns new user authentication.
	CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*Authentication, error)
}

type authenticationsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationsServiceClient(cc *grpc.ClientConn) AuthenticationsServiceClient {
	return &authenticationsServiceClient{cc}
}

func (c *authenticationsServiceClient) CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*Authentication, error) {
	out := new(Authentication)
	err := c.cc.Invoke(ctx, "/app.miniboard.authentications.v1.AuthenticationsService/CreateAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationsServiceServer is the server API for AuthenticationsService service.
type AuthenticationsServiceServer interface {
	// Authenticate
	//
	// Returns new user authentication.
	CreateAuthentication(context.Context, *CreateAuthenticationRequest) (*Authentication, error)
}

// UnimplementedAuthenticationsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationsServiceServer struct {
}

func (*UnimplementedAuthenticationsServiceServer) CreateAuthentication(ctx context.Context, req *CreateAuthenticationRequest) (*Authentication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthentication not implemented")
}

func RegisterAuthenticationsServiceServer(s *grpc.Server, srv AuthenticationsServiceServer) {
	s.RegisterService(&_AuthenticationsService_serviceDesc, srv)
}

func _AuthenticationsService_CreateAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationsServiceServer).CreateAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.authentications.v1.AuthenticationsService/CreateAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationsServiceServer).CreateAuthentication(ctx, req.(*CreateAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.authentications.v1.AuthenticationsService",
	HandlerType: (*AuthenticationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthentication",
			Handler:    _AuthenticationsService_CreateAuthentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentications/v1/authentication_service.proto",
}
