// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/articles/v1/articles_service.proto

package accounts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListArticlesRequest struct {
	// Name of a user who owns articles.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of articles to return.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticlesRequest) Reset()         { *m = ListArticlesRequest{} }
func (m *ListArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticlesRequest) ProtoMessage()    {}
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f020f7979e81b284, []int{0}
}

func (m *ListArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesRequest.Unmarshal(m, b)
}
func (m *ListArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesRequest.Marshal(b, m, deterministic)
}
func (m *ListArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesRequest.Merge(m, src)
}
func (m *ListArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticlesRequest.Size(m)
}
func (m *ListArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesRequest proto.InternalMessageInfo

func (m *ListArticlesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListArticlesRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListArticlesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListArticlesResponse struct {
	// There will be a maximum number of articles returned based on the page_size field int the request.
	Articles []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no more results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticlesResponse) Reset()         { *m = ListArticlesResponse{} }
func (m *ListArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*ListArticlesResponse) ProtoMessage()    {}
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f020f7979e81b284, []int{1}
}

func (m *ListArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesResponse.Unmarshal(m, b)
}
func (m *ListArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesResponse.Marshal(b, m, deterministic)
}
func (m *ListArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesResponse.Merge(m, src)
}
func (m *ListArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_ListArticlesResponse.Size(m)
}
func (m *ListArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesResponse proto.InternalMessageInfo

func (m *ListArticlesResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *ListArticlesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreateArticleRequest struct {
	// Name of the owner.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Article to create.
	Article              *Article `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleRequest) Reset()         { *m = CreateArticleRequest{} }
func (m *CreateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest) ProtoMessage()    {}
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f020f7979e81b284, []int{2}
}

func (m *CreateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest.Unmarshal(m, b)
}
func (m *CreateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest.Merge(m, src)
}
func (m *CreateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest.Size(m)
}
func (m *CreateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest proto.InternalMessageInfo

func (m *CreateArticleRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateArticleRequest) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type Article struct {
	// Name of the resource, for example "users/user1/articles/article1".
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_f020f7979e81b284, []int{3}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListArticlesRequest)(nil), "app.miniboard.users.articles.v1.ListArticlesRequest")
	proto.RegisterType((*ListArticlesResponse)(nil), "app.miniboard.users.articles.v1.ListArticlesResponse")
	proto.RegisterType((*CreateArticleRequest)(nil), "app.miniboard.users.articles.v1.CreateArticleRequest")
	proto.RegisterType((*Article)(nil), "app.miniboard.users.articles.v1.Article")
}

func init() {
	proto.RegisterFile("users/articles/v1/articles_service.proto", fileDescriptor_f020f7979e81b284)
}

var fileDescriptor_f020f7979e81b284 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6a, 0xdb, 0x40,
	0x18, 0x44, 0x72, 0xf1, 0xcf, 0xd7, 0x1a, 0xc3, 0xd6, 0x14, 0xe1, 0xd6, 0xd4, 0x55, 0xa1, 0xa8,
	0x85, 0x4a, 0xd8, 0x6e, 0x2f, 0x85, 0x1e, 0xea, 0xe6, 0x98, 0x43, 0x90, 0x73, 0xca, 0xc5, 0xac,
	0x95, 0x0f, 0xb3, 0xc4, 0xde, 0x55, 0x76, 0xd7, 0x22, 0x38, 0xf8, 0x12, 0xf2, 0x06, 0x79, 0x86,
	0xe4, 0x85, 0xf2, 0x06, 0x21, 0x0f, 0x12, 0xbc, 0xfa, 0xc1, 0x06, 0x83, 0xe2, 0xdb, 0xea, 0xd3,
	0xce, 0x37, 0xb3, 0x33, 0x03, 0xde, 0x52, 0xa1, 0x54, 0x01, 0x95, 0x9a, 0x45, 0x73, 0x54, 0x41,
	0xd2, 0x2f, 0xce, 0x13, 0x85, 0x32, 0x61, 0x11, 0xfa, 0xb1, 0x14, 0x5a, 0x90, 0xcf, 0x34, 0x8e,
	0xfd, 0x05, 0xe3, 0x6c, 0x2a, 0xa8, 0x3c, 0xf7, 0x0d, 0xce, 0xcf, 0xef, 0xfa, 0x49, 0xbf, 0xf3,
	0x69, 0x26, 0xc4, 0x6c, 0x8e, 0x01, 0x8d, 0x59, 0x40, 0x39, 0x17, 0x9a, 0x6a, 0x26, 0xb8, 0x4a,
	0xe1, 0x2e, 0x83, 0xf7, 0xc7, 0x4c, 0xe9, 0x7f, 0x19, 0x20, 0xc4, 0xcb, 0x25, 0x2a, 0x4d, 0x3e,
	0x40, 0x35, 0xa6, 0x12, 0xb9, 0x76, 0xac, 0x9e, 0xe5, 0x35, 0xc2, 0xec, 0x8b, 0x7c, 0x84, 0x46,
	0x4c, 0x67, 0x38, 0x51, 0x6c, 0x85, 0x8e, 0xdd, 0xb3, 0xbc, 0x4a, 0x58, 0xdf, 0x0c, 0xc6, 0x6c,
	0x85, 0xa4, 0x0b, 0x60, 0x7e, 0x6a, 0x71, 0x81, 0xdc, 0xa9, 0x18, 0xa0, 0xb9, 0x7e, 0xba, 0x19,
	0xb8, 0xb7, 0x16, 0xb4, 0x77, 0xb9, 0x54, 0x2c, 0xb8, 0x42, 0x72, 0x04, 0xf5, 0x5c, 0xb0, 0x63,
	0xf5, 0x2a, 0xde, 0xdb, 0x81, 0xe7, 0x97, 0xbc, 0xca, 0xcf, 0x96, 0x84, 0x05, 0x92, 0x7c, 0x83,
	0x16, 0xc7, 0x2b, 0x3d, 0xd9, 0x92, 0x60, 0x1b, 0x09, 0xcd, 0xcd, 0xf8, 0xa4, 0x90, 0x21, 0xa1,
	0xfd, 0x5f, 0x22, 0xd5, 0x98, 0xaf, 0x28, 0x79, 0xf2, 0x08, 0x6a, 0x19, 0x87, 0xd9, 0x77, 0x88,
	0xb8, 0x1c, 0xe8, 0x76, 0xa1, 0x96, 0xcd, 0x08, 0x81, 0x37, 0x9c, 0x2e, 0x30, 0x23, 0x31, 0xe7,
	0xc1, 0x93, 0x0d, 0xad, 0xdc, 0x95, 0x71, 0x9a, 0x2e, 0x79, 0xb0, 0xe0, 0xdd, 0xb6, 0x5b, 0xe4,
	0x57, 0x29, 0xed, 0x9e, 0x20, 0x3b, 0xbf, 0x0f, 0x44, 0xa5, 0x91, 0xb8, 0xdf, 0x6f, 0x1e, 0x9f,
	0xef, 0xec, 0xaf, 0xe4, 0x8b, 0xa9, 0x4d, 0xd2, 0x0f, 0xae, 0x53, 0x37, 0xfe, 0xa6, 0xbd, 0xfc,
	0xb1, 0x2e, 0xea, 0x48, 0xee, 0x2d, 0x68, 0xee, 0x18, 0x4a, 0xca, 0x39, 0xf7, 0x05, 0xd0, 0x79,
	0xb5, 0xaf, 0xee, 0xd0, 0xa8, 0xfb, 0xe9, 0xba, 0xa5, 0xea, 0xd6, 0x7f, 0xf2, 0x0c, 0x46, 0x70,
	0x56, 0xa7, 0x51, 0x24, 0x96, 0x5c, 0xab, 0x69, 0xd5, 0x94, 0x7f, 0xf8, 0x12, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xd4, 0x9c, 0x48, 0x67, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticlesServiceClient is the client API for ArticlesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticlesServiceClient interface {
	// List articles
	//
	// An endpoint to list the user's articles.
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
	// Create article
	//
	// An endpoint to add an article for the user.
	CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*Article, error)
}

type articlesServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticlesServiceClient(cc *grpc.ClientConn) ArticlesServiceClient {
	return &articlesServiceClient{cc}
}

func (c *articlesServiceClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.articles.v1.ArticlesService/ListArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articlesServiceClient) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/app.miniboard.users.articles.v1.ArticlesService/CreateArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticlesServiceServer is the server API for ArticlesService service.
type ArticlesServiceServer interface {
	// List articles
	//
	// An endpoint to list the user's articles.
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	// Create article
	//
	// An endpoint to add an article for the user.
	CreateArticle(context.Context, *CreateArticleRequest) (*Article, error)
}

// UnimplementedArticlesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedArticlesServiceServer struct {
}

func (*UnimplementedArticlesServiceServer) ListArticles(ctx context.Context, req *ListArticlesRequest) (*ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (*UnimplementedArticlesServiceServer) CreateArticle(ctx context.Context, req *CreateArticleRequest) (*Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArticle not implemented")
}

func RegisterArticlesServiceServer(s *grpc.Server, srv ArticlesServiceServer) {
	s.RegisterService(&_ArticlesService_serviceDesc, srv)
}

func _ArticlesService_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlesServiceServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.articles.v1.ArticlesService/ListArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlesServiceServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticlesService_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlesServiceServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.miniboard.users.articles.v1.ArticlesService/CreateArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlesServiceServer).CreateArticle(ctx, req.(*CreateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticlesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.miniboard.users.articles.v1.ArticlesService",
	HandlerType: (*ArticlesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArticles",
			Handler:    _ArticlesService_ListArticles_Handler,
		},
		{
			MethodName: "CreateArticle",
			Handler:    _ArticlesService_CreateArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/articles/v1/articles_service.proto",
}
