name: CI

on:
  push: {}
  pull_request: {}

env:
  GO_VERSION: 1.13.7
  IMAGE_NAME: docker.pkg.github.com/ngalaiko/miniboard/app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Run tests
      run: |
        cd server && go test -race -v ./...

    - name: Build image
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        docker build . -t "${IMAGE_NAME}:${GITHUB_SHA}"
        docker save -o app.tar "${IMAGE_NAME}:${GITHUB_SHA}"

    - name: Upload app.tar
      uses: actions/upload-artifact@v1
      with:
        name: app.tar
        path: app.tar


  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Download app.tar
      uses: actions/download-artifact@v1
      with:
        name: app.tar
        path: .

    - name: Load image
      run: |
        docker load -i app.tar

    - name: Login to registry
      env:
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login \
            -u ngalaiko \
            -p "${DOCKER_PASSWORD}" \
            docker.pkg.github.com

    - name: Push image
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        docker push "${IMAGE_NAME}:${GITHUB_SHA}"

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Set up kubectl
      uses: matootie/dokube@v1.2.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: k8s-1-16-2-do-3-ams3-1580667990888
        expirationTime: 300

    - name: Apply Chart
      run: |
        cd .charts
        helm template miniboard \
          --set "Version=$(git rev-parse HEAD)" \
          | kubectl apply -f-
