name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Run Tests
      env:
        API_URL: https://miniboard.app
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Login to registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HOME: /home/runner/work/_temp/_github_home
      run: |
        # this will create /home/runner/.docker/config.json with credentials
        docker login \
            -u ngalayko \
            -p ${DOCKER_PASSWORD}
        # copy credentials to mount them to the bazel container.
        mkdir -p ${DOCKER_HOME}/.docker
        cp /home/runner/.docker/config.json ${DOCKER_HOME}/.docker/config.json

    - name: Push image
      env:
        API_URL: https://miniboard.app
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" run \
          --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 :docker_push

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Set up kubectl
      uses: matootie/dokube@v1.2.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: k8s-1-16-2-do-3-ams3-1579941791756
        expirationTime: 300

    - name: Apply Chart
      run: |
        cd .charts
        helm template miniboard \
          --set "Version=$(git rev-parse HEAD)" \
          | kubectl apply -f-
