name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Run Tests
      uses: ngalaiko/bazel-action/1.1.0@master
      with:
        args: test //...

    - name: Login to registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HOME: /home/runner/work/_temp/_github_home
      run: |
        # this will create /home/runner/.docker/config.json with credentials
        docker login \
            -u ngalayko \
            -p ${DOCKER_PASSWORD}
        # copy credentials to mount them to the bazel container.
        mkdir -p ${DOCKER_HOME}/.docker
        cp /home/runner/.docker/config.json ${DOCKER_HOME}/.docker/config.json

    - name: Push image
      uses: ngalaiko/bazel-action/1.1.0@master
      with:
        args: run --platforms=@io_bazel_rules_go//go/toolchain:linux_arm :docker_push

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Generate Chart
      run: |
        cd .charts
        helm template miniboard \
          --set "Version=$(git rev-parse HEAD)" > chart.yaml

    - name: Apply Chart
      uses: exelban/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f /github/workspace/.charts/chart.yaml
